SET SESSION storage_engine = "InnoDB";
SET SESSION time_zone = "+0:00";
ALTER DATABASE CHARACTER SET "utf8";

DROP TABLE IF EXISTS thumbnail;
CREATE TABLE IF NOT EXISTS thumbnail(
    id VARCHAR(255) NOT NULL,
    data LONGTEXT NOT NULL,
    url VARCHAR(1024) NOT NULL,
    UNIQUE ID (id)
);
